[package]
name = "advent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
num-bigint = "0.4"
pathfinding = "3.0.5"

[profile.release]
lto = "fat"
codegen-units = 1

